In [263]:
import numpy as np

In [264]:
np.__version__

'1.26.4'

## Creating array

In [265]:
a = np.array([1,2,3,4])

In [266]:
type(a)

numpy.ndarray

In [5]:
a

array([1, 2, 3, 4])

In [267]:
a.dtype   # data type of elements 

dtype('int32')

In [268]:
a.shape

(4,)

In [8]:
langs = np.array(("Java","Python","C","JavaScript"))

In [9]:
langs

array(['Java', 'Python', 'C', 'JavaScript'], dtype='<U10')

In [10]:
a = np.array((1,2,'abc')) 

In [11]:
a

array(['1', '2', 'abc'], dtype='<U11')

#### Difference between Array and list

In [12]:
a = np.array((1,4,6,8,9))
a * 2  # Multiplication 

array([ 2,  8, 12, 16, 18])

In [13]:
a * a

array([ 1, 16, 36, 64, 81])

In [14]:
a + a

array([ 2,  8, 12, 16, 18])

In [269]:
## Python list with * 
pa = [1,4,6,8,9]
pa * 2     # Replication 

[1, 4, 6, 8, 9, 1, 4, 6, 8, 9]

In [16]:
pa + pa     #Concatenation 

[1, 4, 6, 8, 9, 1, 4, 6, 8, 9]

### arange()

In [17]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a.dtype

dtype('int32')

In [270]:
a = np.arange(1,20,2, dtype='int16')
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int16)

#### Other functions to create array 

In [271]:
a = np.full(10, 5)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [21]:
a = np.full((5, 5), 3)  # Array of 5 X 5 and fill it with 3
a

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [22]:
a = np.ones(10)
a, a.dtype

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), dtype('float64'))

In [23]:
a = np.ones(10, dtype = np.int32)
a, a.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), dtype('int32'))

In [272]:
a[0] = 100    # modify element

In [273]:
a

array([100,   5,   5,   5,   5,   5,   5,   5,   5,   5])

In [26]:
# a[0] = 'Abc' # Not possible as array are homegeneous 

In [27]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
a = np.eye(5,5)   # Identity matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random numbers generation

In [29]:
a = np.random.rand(10)
a

array([0.52596838, 0.6153314 , 0.23362604, 0.38930347, 0.38266461,
       0.57223466, 0.24895388, 0.15468584, 0.55848626, 0.98232929])

In [30]:
a[-1]

0.9823292927112154

In [31]:
for n in a[:5]:
    print(n)

0.5259683789392604
0.6153314012384347
0.2336260408353118
0.3893034735938129
0.3826646137550451


In [32]:
a = np.random.randint(1,100,10)   # min, max, size of array 
a

array([55, 15, 71, 25, 80, 91, 54, 17, 68, 40])

In [33]:
a = np.random.randint(1,10,(3,3))
a

array([[5, 2, 4],
       [6, 6, 5],
       [7, 1, 4]])

### linspace()

In [34]:
a = np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [274]:
a, step = np.linspace(1,20,5, retstep = True)  # Return Step value 

In [275]:
a, step 

(array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]), 4.75)

In [276]:
a, step = np.linspace(1,10,5, dtype=np.int32, retstep=True)
a, step

(array([ 1,  3,  5,  7, 10]), 2.25)

### Attributes of ndarray

In [277]:
a = np.random.randint(1,10,(3,3))

In [278]:
a

array([[9, 5, 6],
       [3, 5, 5],
       [5, 3, 2]])

In [279]:
a.ndim, a.size, a.dtype, a.shape

(2, 9, dtype('int32'), (3, 3))

### Indexing and slicing

In [280]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
a[0,0], a[4,0]

(1, 21)

In [281]:
# Nested list in Python
l = [[1,2,3], [10,20,30,40]]
l[1][0]

10

In [282]:
a[4]  # Single row 

array([21, 22, 23, 24, 25])

In [283]:
a[-1,-1]   # Last row , last col 

25

In [46]:
a[-1]   # Last row 

array([21, 22, 23, 24, 25])

In [47]:
a[-1,0], a[0][-1]

(21, 5)

### slicing

In [48]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
a[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [50]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [51]:
a[:,2]  # Column with index 2 

array([ 3,  8, 13, 18, 23])

In [52]:
a[4,3:]

array([24, 25])

In [285]:
b = a[:,-1]   # Last column 
b.shape, b

((5,), array([ 5, 10, 15, 20, 25]))

In [54]:
b = a[:,-1:]   # Last column 
b.shape, b

((5, 1),
 array([[ 5],
        [10],
        [15],
        [20],
        [25]]))

In [55]:
a[-2:,-2:]

array([[19, 20],
       [24, 25]])

In [56]:
# a[5,5]  --> Error 

In [286]:
a[::2]   # Alternate rows 

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [58]:
a[::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [59]:
a[::-1, ::-1]

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [60]:
a[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [61]:
a[-2:, ::-1] # Last two rows and cols in reverse 

array([[20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [62]:
a[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [63]:
# Last two col and alternate rows 
a[::2, -2:]

array([[ 4,  5],
       [14, 15],
       [24, 25]])

In [64]:
# Last two colunms in reverse order 
a[:,:-3:-1]

array([[ 5,  4],
       [10,  9],
       [15, 14],
       [20, 19],
       [25, 24]])

### Index by array

In [287]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
a[[3,6,9]]    # index is an array

array([ 4,  7, 10])

In [67]:
# Can we do it in Python list 
#l = [1,2,3,4]
#print( l[[1,3]])

In [288]:
a[[-1,-5,0]]

array([10,  6,  1])

In [289]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
a [[0,2],[1,3]]

array([ 2, 14])

In [71]:
#a[[0,2],[1,3,4]]   # Error 

In [72]:
a [[1,2,3],[4,4,-1]]

array([10, 15, 20])

### Iterate 

In [73]:
a = np.arange(10)
for n in a:
    print(n, end = ' ')

0 1 2 3 4 5 6 7 8 9 

In [74]:
a = np.random.randint(1,10,(3,3))
a

array([[9, 1, 8],
       [6, 1, 4],
       [5, 8, 3]])

In [75]:
for r in a:
    for c in r:
         if c % 2 == 0:
                print(c)

8
6
4
8


### Boolean Indexing

In [290]:
a = np.random.randint(1,100,5)
a

array([54, 37, 90, 80, 47])

In [291]:
a [ [True,False,True,False, False]]

array([54, 90])

In [292]:
a

array([54, 37, 90, 80, 47])

In [293]:
a % 2 == 0 

array([ True, False,  True,  True, False])

In [294]:
a [ a % 2 == 0]

array([54, 90, 80])

In [295]:
a > 50

array([ True, False,  True,  True, False])

In [82]:
# a [[True,True]]     --> Not valid because array of booleans and indexed array are not of same size

In [296]:
a = np.random.randint(1,100,10)
a

array([25, 12, 22, 31, 52, 86, 60, 82, 78, 62])

In [297]:
evens = a % 2 == 0 
evens

array([False,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [298]:
a [evens]    # a [ a % 2 == 0 ]

array([12, 22, 52, 86, 60, 82, 78, 62])

In [299]:
a[a % 2 == 1]  # Boolean Indexing

array([25, 31])

In [300]:
a2 = a [ a > 50]

In [301]:
a2

array([52, 86, 60, 82, 78, 62])

In [302]:
a = np.random.randint(1,10, (5,5))
a

array([[7, 2, 2, 6, 1],
       [8, 2, 5, 4, 8],
       [4, 8, 2, 1, 5],
       [5, 8, 7, 3, 8],
       [3, 5, 7, 2, 3]])

In [303]:
a > 5

array([[ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [False,  True, False, False, False],
       [False,  True,  True, False,  True],
       [False, False,  True, False, False]])

In [304]:
a [ a > 5 ] 

array([7, 6, 8, 8, 8, 8, 7, 8, 7])

#### Masking

In [94]:
(a > 2) & (a < 8)

array([[ True,  True, False, False,  True],
       [ True, False,  True, False, False],
       [ True, False,  True, False, False],
       [False, False, False,  True, False],
       [ True,  True, False,  True,  True]])

In [95]:
a [ (a > 2) & (a < 8)]  # Anding 

array([3, 5, 3, 4, 4, 7, 3, 6, 7, 6, 7, 5])

In [96]:
#a [(a > 2) and (a < 8)]  # Anding in python 

In [97]:
a = np.random.randint(1,10,10)
a

array([3, 2, 3, 4, 1, 7, 1, 1, 7, 4])

In [98]:
ba1 = a >= 1
print(ba1)
ba2 = a <= 5
print(ba2)

[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True False  True  True False  True]


In [99]:
ba1 | ba2    # Oring 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [100]:
a [ba1 & ba2]

array([3, 2, 3, 4, 1, 1, 1, 4])

In [101]:
def isprime(n):
    for i in range(2,n//2 + 1):
        if n % i == 0 :
               return False
            
    return True

In [102]:
# Returns a list of booleans 
def prime(a):
    lst = []
    for n in a:
         lst.append(isprime(n))   # Append true or false 
        
    return lst  # List of booleans 

In [305]:
a = np.random.randint(1,100,10)
a

array([59, 17, 77, 77, 45, 28, 72, 36, 58, 57])

In [306]:
print(prime(a))

[True, True, False, False, False, False, False, False, False, False]


In [307]:
a[prime(a)]

array([59, 17])

In [308]:
prime_booleans = [isprime(n) for n in a] # List comprehension for boolean indexing 

In [309]:
prime_booleans

[True, True, False, False, False, False, False, False, False, False]

In [310]:
a[prime_booleans]  

array([59, 17])

In [109]:
## Iterate array a and display all prime numbers 

### Array Operations

In [311]:
a = np.array([1,2,3,4,5])

In [312]:
b = a + 10.5

In [313]:
b, b.dtype, a.dtype

(array([11.5, 12.5, 13.5, 14.5, 15.5]), dtype('float64'), dtype('int32'))

In [113]:
print(b)
b -= 5        # inplace  b = b - 5
print(b)

[11.5 12.5 13.5 14.5 15.5]
[ 6.5  7.5  8.5  9.5 10.5]


In [114]:
# Diff sizes for array 
a1 = np.arange(4)
a2 = np.arange(5)
#a1 + a2    # Error

In [314]:
a1 = np.arange(5)
a2 = np.arange(5)
a1 == a2    

array([ True,  True,  True,  True,  True])

#### all() vs. any()

In [315]:
ba = np.array([True,False,True])
print(ba.all())
print(ba.any())

False
True


In [117]:
a1 == a2 

array([ True,  True,  True,  True,  True])

In [118]:
(a1 == a2).all()   # True if all elements are equal 

True

In [119]:
(a1 == a2).any() 

True

In [316]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,4,3,2,4])

In [317]:
(a1 > a2).any() 

True

In [122]:
# Do we have any even number in the array
a = np.random.randint(1,100,10)
print(a)
evens = a % 2 == 0 
print(evens.any())

[14  9 96 93 61 88 91 18 87 13]
True


### Methods of ndarray

In [318]:
a = np.random.randint(1,100,10)
print(a)
b = np.zeros(5)
print(b)

[ 5 52 92 15  5 55  8 35 36 96]
[0. 0. 0. 0. 0.]


In [319]:
a.sum()

399

In [125]:
a.any()  # Is there any true value (0 is false, non-zero is true)

True

In [126]:
b.any()

False

In [127]:
a.all()   # Are all true

True

In [320]:
## No.of odd numbers in each row 
a = np.random.randint(1,100,(6,6))
print(a)
for idx, row in enumerate(a):
    print(idx,(row % 2 == 1).sum())

[[10 14  7 16 82 84]
 [48 52 66  1 57 24]
 [97 52 86 36 49 57]
 [35 57 23 50  1 19]
 [84 96 43 78 97 40]
 [37 10 16  5 88 23]]
0 1
1 2
2 3
3 5
4 2
5 3


In [129]:
np.array([True,False,True]).sum()   # True means 1, False means 0 

2

In [321]:
## How many subjects student passed
marks = np.random.randint(1,100,(6,6))
print(marks)
for row in marks:
    #print(row >= 50)
    print((row >= 50).sum())

[[92 66 64 58 45 71]
 [10 18 61 12 42  6]
 [73 29 73 78 67 49]
 [44 66 28 51 31 92]
 [99 11 64 22 60 47]
 [35 74 14  7 22 11]]
5
1
4
3
3
1


In [131]:
marks.mean()  # Total mean for entire array 

62.77777777777778

In [132]:
for row in marks:
    print(int(row.mean()))   #  Mean for each student 

48
70
61
74
66
55


In [133]:
marks >= 50

array([[ True, False,  True, False,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [False,  True,  True, False,  True,  True],
       [ True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True, False,  True,  True, False, False]])

In [134]:
(marks >= 50).sum()  # total no. of students passed

25

#### Using axis parameter

In [325]:
marks = np.random.randint(1,100,(3,3))

In [326]:
marks

array([[60, 53,  8],
       [82,  8,  3],
       [70, 93, 58]])

In [327]:
marks.sum()

435

In [328]:
marks.sum(axis=0) # Column-wise total 

array([212, 154,  69])

In [329]:
marks.sum(axis=1) # Row-wise total 

array([121,  93, 221])

In [140]:
(marks >= 50).sum(axis=0)  # Column-wise Sum (Subject)

array([4, 2, 2, 4])

In [141]:
(marks >= 50).sum(axis=1)  # row-wise Sum (Student wise)3

array([0, 3, 1, 3, 3, 2])

In [142]:
marks.sum(axis = 1) # total marks for each student

array([ 84, 249, 181, 276, 236, 244])

In [330]:
marks.mean(axis=1)

array([40.33333333, 31.        , 73.66666667])

In [331]:
marks.mean(axis=1).max()

73.66666666666667

In [332]:
# higest marks for each student
marks.max(axis = 1)

array([60, 82, 93])

In [146]:
# sum of alternate rows 
marks[::2].sum(axis=1)

array([ 84, 181, 236])

In [147]:
a = np.random.randint(1,100,10)
a.mean(),a.std()

(54.4, 28.171616922001476)

In [333]:
a = np.random.randint(1,10,5)
print(a)
print(a.cumsum())

[6 1 7 6 2]
[ 6  7 14 20 22]


In [334]:
a = np.random.randint(1,10,(3,3))
print(a)

[[4 2 2]
 [9 2 1]
 [8 1 9]]


In [335]:
a.cumsum(axis = 1)  # Row-wise cumulative sum

array([[ 4,  6,  8],
       [ 9, 11, 12],
       [ 8,  9, 18]])

In [336]:
a.cumsum(axis = 0)

array([[ 4,  2,  2],
       [13,  4,  3],
       [21,  5, 12]])

In [337]:
a = np.random.randint(1,10,10)
a

array([7, 8, 2, 1, 5, 3, 2, 7, 8, 4])

#### argmax(), argmin()

In [338]:
a.argmax(), a.argmin()    # index for max and min values in the array 

(1, 3)

In [339]:
a = np.array([5,3,10,2,1])
a.argsort()

array([4, 3, 1, 0, 2], dtype=int64)

In [340]:
sa = a [ a.argsort() ]
sa

array([ 1,  2,  3,  5, 10])

In [156]:
sa.searchsorted(3)

2

In [157]:
l = a.tolist()

In [158]:
type(l)

list

#### Sorting 

In [341]:
a = np.array( (6,7,5,3,2))

In [342]:
sorted(a, reverse=True)  # Python function 

[7, 6, 5, 3, 2]

In [343]:
a

array([6, 7, 5, 3, 2])

In [344]:
a.sort()  # Inplace sorting 

In [345]:
a

array([2, 3, 5, 6, 7])

#### 2D array

In [164]:
a = np.random.randint(1,10,(3,3))
a

array([[3, 7, 9],
       [1, 6, 3],
       [7, 2, 8]])

In [165]:
a.sort() # Sort rows 
print(a)

[[3 7 9]
 [1 3 6]
 [2 7 8]]


In [346]:
a = np.random.randint(1,10,(3,3))
print(a)

[[5 2 1]
 [4 4 4]
 [7 9 3]]


In [167]:
a.sort(axis = 0)
print(a)

[[4 1 1]
 [7 8 2]
 [9 9 5]]


In [349]:
a = np.random.randint(1,10,(3,3))
print(a)
np.sort(a, axis=None)  # Sorting entire 2d array after flattening it 

[[1 1 6]
 [5 7 5]
 [8 8 1]]


array([1, 1, 1, 5, 5, 6, 7, 8, 8])

In [169]:
a

array([[9, 9, 1],
       [8, 7, 7],
       [5, 4, 4]])

In [170]:
np.sort(a)  # Row-wise sorting 

array([[1, 9, 9],
       [7, 7, 8],
       [4, 4, 5]])

In [350]:
a = np.random.randint(1,10,(3,3))
print(a)

[[5 4 5]
 [1 4 7]
 [5 7 2]]


In [351]:
np.sort(a, axis=None).reshape((3,3))

array([[1, 2, 4],
       [4, 5, 5],
       [5, 7, 7]])

### Copy vs. View 

In [173]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
b = a[5:]  # b is a View into a 
b

array([ 6,  7,  8,  9, 10])

In [175]:
b[0] = 20

In [176]:
b

array([20,  7,  8,  9, 10])

In [177]:
a

array([ 1,  2,  3,  4,  5, 20,  7,  8,  9, 10])

In [178]:
b[:] = 0

In [179]:
a

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])

In [180]:
a[9] = 100
b

array([  0,   0,   0,   0, 100])

In [181]:
b[:2] = [10,20]
b,a

(array([ 10,  20,   0,   0, 100]),
 array([  1,   2,   3,   4,   5,  10,  20,   0,   0, 100]))

In [182]:
c = b[:3]

In [183]:
c[0] = 100

In [184]:
a

array([  1,   2,   3,   4,   5, 100,  20,   0,   0, 100])

In [185]:
a1 = np.arange(1,11)
a2 = a1.copy()
a2[0] = 1000
a1,a2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10]))

In [186]:
a = np.array((1,2,3))
b = a[:]
del a    # Delete original 
print(b)

[1 2 3]


#### Boolean indexing in copy vs. view

In [187]:
# Array of booleans  
a = np.array((1,2,3,4,5))
na = a[a > 3]  # You get a copy of a 
na [0] = 100
a, na

(array([1, 2, 3, 4, 5]), array([100,   5]))

In [188]:
# Array of indexes 
a = np.array((1,2,3,4,5))
na = a[[1,3]]  # You get a copy of a 
na[0] = 100
a, na

(array([1, 2, 3, 4, 5]), array([100,   4]))

### Universal Functions
These are functions in Numpy module

In [189]:
a = np.arange(1,10)
b = np.arange(11,20)
a + b

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [190]:
np.add(a,b)

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [191]:
np.lcm(10,5), np.gcd(10,30)

(10, 10)

In [192]:
np.sqrt( [10,15,30,40])

array([3.16227766, 3.87298335, 5.47722558, 6.32455532])

In [193]:
np.sign(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

### Stacking and splitting 

In [194]:
a1 = np.arange(1,5).reshape(2,2)
a1

array([[1, 2],
       [3, 4]])

In [195]:
a2 = np.arange(10,16).reshape(2,3)
a2

array([[10, 11, 12],
       [13, 14, 15]])

In [196]:
np.hstack((a1,a2))

array([[ 1,  2, 10, 11, 12],
       [ 3,  4, 13, 14, 15]])

In [197]:
a2 = np.arange(10,14).reshape(2,2)
a2

array([[10, 11],
       [12, 13]])

In [198]:
np.vstack((a1,a2))

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

In [199]:
np.concatenate((a1,a2))   # Vertical stacking - defualt axis = 0 

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

In [200]:
np.concatenate((a1,a2), axis=1)  # Horizontal stacking 

array([[ 1,  2, 10, 11],
       [ 3,  4, 12, 13]])

In [201]:
a1 = np.random.randint(1,10,(2,2))
a2 =  np.random.randint(1,10,(3,2))
# np.hstack((a1,a2))
# np.vstack((a1,a2))

#### Splitting

In [202]:
a = np.arange(1,19).reshape(6,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [203]:
np.vsplit(a,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [204]:
a1, a2 = np.vsplit(a,2) # unpacking 

In [205]:
a1.shape, a2.shape

((3, 3), (3, 3))

In [206]:
np.vsplit(a, (1, 4))   # Split at row 1 and row 4 

[array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [207]:
np.vsplit(a, (4,))

[array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [208]:
np.hsplit(a, (2,))  

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [209]:
a1, a2, a3 = np.vsplit(a, (1,4))   # Unpacking 

In [210]:
a1.shape, a2.shape, a3.shape 

((1, 3), (3, 3), (2, 3))

In [211]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [212]:
a1, a2 = np.vsplit(a,2)

In [213]:
a1, a2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [214]:
a1[0,0] = 100

In [215]:
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18]])

### Reshaping array

In [216]:
a = np.arange(1,10)
b = a.reshape(3,3)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [217]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [218]:
b[0,0] = 100    # B is a view to A
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [219]:
c = np.reshape(a, (-1,3))  # decide the number of rows 
c

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [220]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [221]:
np.reshape(a, (3,3), order='F')

array([[100,   4,   7],
       [  2,   5,   8],
       [  3,   6,   9]])

In [222]:
np.reshape(a, (3,3))   # C order

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

#### ravel()

In [223]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [224]:
ar  = a.ravel()  # Returns a 1d array which is a view 
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [225]:
ar[0] = 10

In [226]:
a

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

#### flatten()

In [227]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [228]:
fa = a.flatten()  # Copy 
fa

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [229]:
fa[0] = 1000
fa, a

(array([1000,    1,    2,    3,    4,    5,    6,    7,    8]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [230]:
a.flatten('F')  # Column-major - Fortran

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

#### reshape()

In [231]:
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [232]:
a.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [233]:
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

#### resize() - inplace resize

In [234]:
a = np.arange(20)
print(a)
a.resize(2,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [235]:
a = np.arange(10)
print(a)
a.resize(5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


### Linear Algebra

#### Transpose

In [236]:
a = np.arange(1,21).reshape(4,5)
print(a)
print(a.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [237]:
a = np.random.randint(1,10, (5,5))
a

array([[8, 1, 6, 5, 6],
       [7, 2, 3, 7, 8],
       [4, 2, 9, 3, 3],
       [9, 1, 9, 3, 9],
       [9, 3, 1, 9, 2]])

In [238]:
np.linalg.inv(a)

array([[-0.09863014, -0.18575342, -0.12767123,  0.23726027,  0.16273973],
       [-1.31506849,  0.12328767,  0.16438356,  0.63013699,  0.36986301],
       [ 0.2       , -0.04      ,  0.12      , -0.12      , -0.08      ],
       [ 0.54520548,  0.11013699,  0.06684932, -0.45041096, -0.14958904],
       [-0.1369863 ,  0.17534247, -0.03287671,  0.0739726 , -0.0739726 ]])

In [239]:
a = np.random.randint(1,5,(3,4))
b = np.random.randint(1,5,(4,2))
a,b

(array([[4, 3, 4, 3],
        [3, 4, 2, 4],
        [4, 2, 4, 3]]),
 array([[3, 3],
        [3, 3],
        [1, 4],
        [3, 1]]))

In [240]:
a @ b   #  rows form a  X cols of b 

array([[34, 40],
       [35, 33],
       [31, 37]])

In [241]:
a.dot(b)

array([[34, 40],
       [35, 33],
       [31, 37]])

In [242]:
np.arange(1,10).reshape(3,3) * np.arange(1,10).reshape(3,3)    # Normal product (multiplication)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [243]:
np.arange(1,10).reshape(3,3) @ np.arange(1,10).reshape(3,3)  # Dot product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Linear Regression with multiple variables using Linalge

In [244]:
X = np.array([[1,1000,2],[1,2000,3],[1,750,1]]) # 1,Size, No.bed rooms

In [245]:
X,X.shape

(array([[   1, 1000,    2],
        [   1, 2000,    3],
        [   1,  750,    1]]),
 (3, 3))

In [246]:
coef = np.array([200000,5000,200000])  # Intercept and b1, b2 (Slope)
coef.shape

(3,)

In [247]:
y = X @ coef
y

array([ 5600000, 10800000,  4150000])

In [248]:
X.dot(coef)

array([ 5600000, 10800000,  4150000])

### Broadcasting

In [249]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [250]:
a + 10   # 10 is broadcast to array of 5 elements

array([10, 11, 12, 13, 14])

In [251]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [252]:
a + 10     # 10 is broadcast to (2,2)

array([[10, 11],
       [12, 13]])

In [253]:
a

array([[0, 1],
       [2, 3]])

In [254]:
a + np.array([1,2])

array([[1, 3],
       [3, 5]])

In [255]:
#a + np.array([2,2,3])

In [256]:
b = np.random.randint(1,5,(3,6))
c = np.random.randint(1,5,(3,1))

In [257]:
print(b)
print(c)

[[4 4 2 2 1 1]
 [2 2 1 4 4 4]
 [1 1 4 4 1 3]]
[[4]
 [1]
 [3]]


In [258]:
b + c  # c is broadcast to 6 cols 

array([[8, 8, 6, 6, 5, 5],
       [3, 3, 2, 5, 5, 5],
       [4, 4, 7, 7, 4, 6]])

In [259]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [260]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [261]:
a + b

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [ ]:
a[:,:4] + b

In [ ]:
a = np.arange(9)
b = np.arange(3)
print(a)
print(b)

In [ ]:
a.reshape((3,3)) + b

## Image processing

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as image
from scipy import misc

In [ ]:
img = misc.face()
type(img), img.shape, img.size

In [ ]:
plt.imshow(img)

In [ ]:
img.dtype

In [ ]:
img[0,0]   # Colors at 0,0

In [ ]:
img[0,0,2]  # Blue at 0,0 

In [ ]:
img[-1,-1]   # Last pixel 

In [ ]:
newimg = img.copy()

In [ ]:
newimg[:100,:100,:] = [0,0,0]  # red patch in upper left corner (100 x 100)

In [ ]:
plt.imshow(newimg)

In [ ]:
newimg[-100:,-100:,:] = [0,0,255]  # Blue patch at the bottom right corner 

In [ ]:
plt.imshow(newimg)

In [ ]:
face = img[200:500, 450:850]

In [ ]:
plt.imshow(face)

In [ ]:
face2 = img.copy()
f1, f2 = np.vsplit(face2, (600,))
plt.imshow(f1)

In [ ]:
plt.imshow(f2)

In [ ]:
plt.imshow(np.vstack((f1,f2)))

In [ ]:
(face2[:,:,2] == 0).sum()     # How many pixels have blue color set to zero

In [ ]:
(face2[:,:,0] > 200).sum()  # How many pixels have red > 200

In [ ]:
newimg = img.copy()
newimg[:,:,2] = 0    # Set blue part of image to 0
plt.imshow(newimg)

In [ ]:
gimg = misc.ascent()
gimg.shape

In [ ]:
gimg[0,0]

In [ ]:
plt.imshow(gimg)

In [ ]:
gimg.size

In [ ]:
(gimg > 200).sum()

In [ ]:
(gimg == 255).sum()

In [ ]:
plt.gray()
plt.imshow(gimg)